config/routes.rb
Rails.application.routes.draw do
  resources :payments
  get 'static_pages/home_logged_user'
  get '/tickets', to: 'tickets#index'

  post '/paymentNotification', to: 'payments#receive_and_update'
  post '/tickets/new', to: 'tickets#create'

  post '/password/reset', to: 'users#enviar_mail_recuperar_contrasenia'

  resources :cars
  resources :rents
  resources :payments
  resources :tickets
  devise_for :users, components: {registrations: 'registrations', sessions: 'sessions'} #Las de devise siempre tienen que estar encima de las de USER

  resources :users, only: [:show]

  resources :users do
	  member do
	  	patch :update_rango
		patch :baja_y_alta_supervisores
		patch :bloquear_usuario
	  end
  end

  resources :rents do
	member do
		patch :terminar_alquiler
	end
  end

  resources :cars do
	member do
		patch :dar_de_baja
    patch :dar_de_alta
	end
  end

  root to: "static_pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :payments, :dependent => :destroy # Cada usuario posee un historial de pagos
	has_many :rents, :dependent => :destroy #Cada usuario tiene multiples alquileres
	has_one_attached :file

  	enum genero: [:Femenino, :Masculino]
	enum :rango, [:Admin, :Supervisor, :Usuario, :No_Aceptado, :A_Verificar, :Baneado], default: :A_Verificar #Los rangos de el usuario

	validates :email, presence: true, uniqueness: true #se fija si esta puesto y si es unico en el formulario/en la consola
	validates :dni, presence: true, uniqueness: true  
	validates :telephone, presence: true, numericality: true, uniqueness: true
	validates :birthdate, presence: true
	validate :en_edad
	validates_format_of :dni,:with => /\A([a-zA-Z]{0,3}[0-9]{6,9})?\z/, :message => "o numero de pasaporte incorrecto. Pon uno en formato adecuado."
	validates_format_of :email,:with => Devise::email_regexp #Se fija el formato de el email
	validate :documento_puesto
	

	private
	def en_edad
		if (!birthdate.nil?)
        	if (((Date.today.year - birthdate.year) < 21))  #Tuve que hacer 3 ifs sino no funciona el codigo, no se porque
           	 	errors.add(:base, "Debes ser mayor a 21.")
       		elsif (((Date.today.year - birthdate.year) == 21) && (Date.today.month < birthdate.month))
				errors.add(:base, "Debes ser mayor a 21.")
			elsif (((Date.today.year - birthdate.year) == 21) && (Date.today.month == birthdate.month) && (Date.today.day < birthdate.day))
				errors.add(:base, "Debes ser mayor a 21.")
			end
		end
    end

	def documento_puesto
		if(!file.attached?)
			errors.add(:base, "Documentos necesarios")
		end
	end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
   def new
     super
   end

  # POST /resource/confirmation
   def create
     super
   end

  # GET /resource/confirmation?confirmation_token=abcdef
   def show
     super
   end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
   def new
     super
   end

  # POST /resource/password
   def create
     super
   end

  # GET /resource/password/edit?reset_password_token=abcdef
   def edit
     super
   end

  # PUT /resource/password
   def update
     super
   end


  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
   def cancel
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:dni, :genero, :birthdate, :telephone, :email, :password, :password_confirmation, :name, :file])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     root_path
   end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     super(resource)
   end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'json'

	def show
  		@user = User.find(params[:id])
	end
	
	def update_rango
		@user = User.find(params[:id])
		@user.update(rango: params[:rango])
		render action: "index", notice: 'Rango cambiado'
	end

	def baja_y_alta_supervisores #Tambien sirve para desbloquear usuarios.
		@user = User.find(params[:id])
		@user.update(rango: params[:rango])
		redirect_to user_url(@user), notice: 'Rango cambiado'
	end 

	def bloquear_usuario
		@user = User.find(params[:id])
		if (@user.Supervisor? && current_user.Supervisor?)
			redirect_to user_url(@user), alert: "No tiene los permisos para efectuar este bloqueo."
		elsif
			if (@user.update(rango: "Baneado"))
				redirect_to user_url(@user), notice: "Usuario bloqueado."
			end
		end
	end

	# recibe un metodo post desde la vista de recuperar contrasenia
	def enviar_mail_recuperar_contrasenia
		mail = request.params['email']
		@user = User.find_by email: mail
		if @user != nil
			puts @user.name
			if PasswordMailer.with(user: @user).reset_password.deliver_now
				redirect_to new_user_password_path, notice: 'Se ha enviado un correo con un enlace para restablecer su contraseña'

			end
		else
			redirect_to new_user_password_path, alert: 'El e-mail ingresado no se encuentra registrado'
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<head>
<%= stylesheet_link_tag 'bootstrap', 'login-styles' %>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


</head>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>


<%= ensure_log %>

<body>
<div class="container-xl py-5 justify-content-center">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>Gestión de usuarios</h2>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>	
                        <th>DNI</th>					
                        <th>Estado</th>
                        <th>Rango actual</th>
                        <th>Perfil</th>
                        <th>Documentación</th>
                        <th>Validar?</th>
                        <th>Alquilando?</th>
                    </tr>
                </thead>
                <tbody>
                    <% User.all.each do |user| %>
                        <tr>
                            <td><%= user.id %></td>
                            <td><%= user.name %></td>
                            <td><%= user.dni %></td> 
                            <td>                          
                            <% if (user.A_Verificar?) %>
                                No verificado
                            <% elsif %>
                                <% if(user.No_Aceptado?) %>                          
                                Rechazado
                                <% elsif %>
                                    Verificado
                                <%end%>
                            <% end %>
                            </td>
                            <td><%= user.rango %></td>
                            <td><%= link_to "Perfil",user, :class => "btn btn-primary" %></td>
                            <td> 
                            <% if (user.file.attached?) %>
                                <%= link_to "Descargar", user.file, download: '', :class => "btn btn-primary" %>
                            <% elsif %>
                                Debe resubir documentacion
                            <% end %>
                            </td>
                            <td class='justify-content-center align-items-center'>
                            <% if (user.A_Verificar?) %>
                                <%= button_to 'Aceptar', update_rango_user_path(user, rango: 'Usuario'), method: :patch, class: "btn btn-sm btn-success m-1" %>
                                <%= button_to 'Rechazar', update_rango_user_path(user, rango: 'No_Aceptado'), method: :patch, class: "btn btn-sm btn-danger m-1" %>
                            <% end %>
                            </td>
                            <td>
                                <% if (user.alquilando?) %>
                                  Si 
                                  <div>
                                  <%= link_to "Alquiler actual", user.rents.last, :class => "btn btn-primary" %>
                                  </div>
                                <%elsif%>
                                  No
                                <% end %>
                            </td>            
                        </tr>
                    <% end %>
                </tbody>
            </table>
    </div>
    </div>
</div>     
</body>
</html>

<script>
$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip();
});
</script>

app/views/users/new.html.erb
<h1>REGISTRARSE</h1>

<%= simple_form_for @user do |u|%>
	<%= u.error_notification %>
	<%= u.input :mail, placeholder: "Inserte su Email", label: 'Email', class: "form-control mb-2" %>
	<%= u.input :password, placeholder: "Inserte su Contrasena", label: 'Contrasena', class: "form-control mb-2" %>
	<%= u.input :dni, placeholder: "Inserte su DNI", class: "form-control mb-2" %>
	<%= u.input :nombre, placeholder: "Inserte su Nombre", label: 'Nombre', class: "form-control mb-2" %>
	<%= u.input :genero, :label => "Genero", :collection => ["Masculino","Femenino"], :selected => "Masculino" %>
	<%= u.input :fecha_nacimiento, label: 'Fecha de nacimiento', class: "form-control mb-2" %>
	<%= u.input :telefono, placeholder: "Inserte su numero de Telefono", label: 'Telefono', class: "form-control mb-2" %>
    <%= u.submit "Registrar", class: "btn btn-primary mb-2" %>
<%end%>

app/views/users/show.html.erb
<p style="color: red"><%= alert %></p>
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'rent-index-style'%>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
</head>

<%= ensure_log %>
<div class="container">
    <div class="main-body">  
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4><%= @user.name %></h4>
                    </div>
					<div class="mt-3">
                  <% if (!(@user.rango == 'Usuario')) %>
                      <h4 class="p-3 mb-2 bg-gradient-light text-dark"><%= @user.rango %></h4>
                  <% end %>
                  </div>
                     <% if (!@user.Admin? && (current_user.Admin? || current_user.Supervisor?)) %>
					<div class="mt-3">
                      <h4 class="p-3 mb-2 bg-dark text-white"> Panel de control </h4>
                    </div>
                     <% end %>
					<div class="mt-3">
					   <% if current_user.Admin? %>
                       		<% if (@user.Supervisor?) %>
                        	        <%= button_to 'Remover supervisor', baja_y_alta_supervisores_user_path(@user, rango: 'Usuario'), method: :patch, class: "btn btn-sm btn-danger" %>
                       		<% elsif (@user.Usuario?) %>
                        	        <%= button_to 'Convertir a supervisor', baja_y_alta_supervisores_user_path(@user, rango: 'Supervisor'), method: :patch, class: "btn btn-sm btn-success" %>
					   		<% end %>
					   <% end %>
                    </div>
					<div class="mt-3">
					   <% if (!@user.Admin? && (current_user.Admin? || current_user.Supervisor?)) %>
                       		<% if (!@user.Baneado?) %>
                       	         <%= button_to 'Bloquear', bloquear_usuario_user_path(@user), method: :patch, class: "btn btn-sm btn-danger" %>
                       		<% else %>
                       	         <%= button_to 'Desbloquear', baja_y_alta_supervisores_user_path(@user, rango: 'Usuario'), method: :patch, class: "btn btn-sm btn-success" %>
					   		<% end %>
					   <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Nombre</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Telefono</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.telephone %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Fecha de nacimiento</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    <%= @user.birthdate %>
                  </div>
                </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Numero de documento</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @user.dni %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-primary"  <%= link_to "Editar", edit_user_registration_path %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>