config/routes.rb
Rails.application.routes.draw do
  resources :payments
  get 'static_pages/home_logged_user'
  get '/tickets', to: 'tickets#index'

  post '/paymentNotification', to: 'payments#receive_and_update'
  post '/tickets/new', to: 'tickets#create'

  post '/password/reset', to: 'users#enviar_mail_recuperar_contrasenia'

  resources :cars
  resources :rents
  resources :payments
  resources :tickets
  devise_for :users, components: {registrations: 'registrations', sessions: 'sessions'} #Las de devise siempre tienen que estar encima de las de USER

  resources :users, only: [:show]

  resources :users do
	  member do
	  	patch :update_rango
		patch :baja_y_alta_supervisores
		patch :bloquear_usuario
	  end
  end

  resources :rents do
	member do
		patch :terminar_alquiler
	end
  end

  resources :cars do
	member do
		patch :dar_de_baja
    patch :dar_de_alta
	end
  end

  root to: "static_pages#home"
end

app/models/rent.rb
class Rent < ApplicationRecord
	
	belongs_to :user
	belongs_to :car

	accepts_nested_attributes_for :car
	validates :tiempo, presence: true

	validate :con_saldo, on: :create
	validate :sin_cooldown, on: :create
  validate :no_mas_de_24, on: :update
  #validate :no_antes, on: :update

	def con_saldo
        if (user.saldo < precio)
            errors.add(:precio, "No tiene el saldo suficiente.")
        end
    end

	def sin_cooldown
		tiempobuffer= DateTime.now
		tiempobuffer= tiempobuffer.change(hour: (tiempobuffer.hour-3), min: tiempobuffer.minute)
		if !(Rent.where(user_id: user.id).where(car_id: car.id).where("tiempo > ?", tiempobuffer).empty?)
			errors.add(:tiempo, "No puede volver a alquilar este auto por cooldown")
		end
	end
  
  def no_mas_de_24
    tiempobuffer = created_at.change(day: (created_at.day+1))
    if (tiempo > tiempobuffer)
      errors.add(:tiempo, "No se puede alquilar mas de 24 horas")
    end
  end
  
  #def no_antes
  #  if (tiempo < tiempo_original)
  #    errors.add(:tiempo, "Selecciona una hora posterior a tu pedido original")
  #  end
  #end

end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: %i[ show edit update destroy ]

  # GET /rents or /rents.json
  def index
    @rents = Rent.where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /rents/1 or /rents/1.json
  def show
	@rent = Rent.find(params[:id])
	@hour = @rent.tiempo.hour - DateTime.now.hour 
	@minute= @rent.tiempo.min - DateTime.now.min
 	if (DateTime.now.day < @rent.tiempo.day)
		@hour= @hour+24
	end
	if (DateTime.now.min > @rent.tiempo.min)
		@minute= @minute+60
	end
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents or /rents.json
  def create
	  #@funca = params[:car_id].to_i
    @rent = Rent.new(rent_params)
	  @rent.user_id = current_user.id
	  #@rent.fecha = DateTime.now
	  if (!@rent.tiempo.nil?)
	  	if (@rent.tiempo < DateTime.now)
	  		@rent.tiempo = @rent.tiempo.change(day: (@rent.tiempo.day + 1))
	  	end
	  @rent.precio = (((@rent.tiempo - DateTime.now)/60)/60) * 1000
    #@rent.tiempo_original = @rent.tiempo
	  end
    respond_to do |format|
      if @rent.save
	  @rent.car.update(alquilado: true)
	    @rent.user.update(alquilando: true)
        format.html { redirect_to rent_url(@rent), notice: "Alquiler realizado." }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new, status: :unprocessable_entity } #No guarda los params => hay error
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1 or /rents/1.json
  def update
    tiempo_anterior= Rent.find(params[:id]).tiempo
    tiempo = Rent.new(rent_params).tiempo
    if (tiempo < DateTime.now)
      tiempo = tiempo.change(day: (tiempo.day + 1))
    end
    if (tiempo <= tiempo_anterior)
       redirect_to rent_url(Rent.find(params[:id])), alert: "No puede alquilar por menos tiempo. Verifique su tiempo restante."
    else
      params[:rent][:tiempo] = tiempo
      respond_to do |format|
        if @rent.update(rent_params)   #terrible negreada mal programada pero bueno, no funciona si toco los params
          @rent.update(precio: (@rent.precio + ((((@rent.tiempo - tiempo_anterior)/60)/60) * 2000)))
          format.html { redirect_to rent_url(@rent), notice: "Alquiler extendido." }
          format.json { render :show, status: :ok, location: @rent }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @rent.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /rents/1 or /rents/1.json
  def destroy
    @rent.destroy

    respond_to do |format|
      format.html { redirect_to rents_url, notice: "Rent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def terminar_alquiler
	@rent = Rent.find(params[:id])
	if (DateTime.now > @rent.tiempo)
		excedente = -((((@rent.tiempo - DateTime.now)/60)/60) * 4000) #Se cobra el exceso de tiempo
		@rent.update(precio: (@rent.precio + excedente))
	end
	@rent.update(tiempo: DateTime.now)
	@rent.update(combustible_gastado: rand(@rent.car.tanque)) #Por ahora el combustible gastado es generado al azar.
	comb_gastado= (@rent.combustible_gastado * 160)
	@rent.update(precio: (@rent.precio + comb_gastado))
	@rent.update(activo: false)
	@rent.car.update(alquilado: false)
	@rent.user.update(alquilando: false, saldo: (@rent.user.saldo - @rent.precio))
	redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rent_params
      params.require(:rent).permit(:precio, :fecha, :car_id, :tiempo)
    end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_with(model: rent) do |form| %>
  <% if rent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
        <% rent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tiempo, '¿Hasta cuando?', style: "display: block" %>
    <%= form.time_field :tiempo %>
  </div>		

	<%= form.hidden_field :car_id, value: params[:autito] %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rents/_rent.html.erb
<div id="<%= dom_id rent %>">
  <p>
    <strong>Precio:</strong>
    <%= rent.precio %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= rent.created_at %>
  </p>

</div>

app/views/rents/edit.html.erb
<head>
<%= stylesheet_link_tag 'bootstrap', 'wallet-styles' %>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>



<%= form_with(model: @rent) do |form| %>
  <% if @rent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
        <% @rent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>






<br>






<div class="container">
                <div class="row m-0">
                    <div class="col-12 px-4">
                        <div class="d-flex align-items-end mt-4 mb-2">

                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="textmuted">Precio por hora de extensión</p>
                            <p class="fs-14 fw-bold"><span class="fas fa-dollar-sign pe-1"></span>2,000</p>		
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <p class="textmuted fw-bold">Total</p>
                            <div class="d-flex align-text-top ">
                                <span class="fas fa-dollar-sign mt-1 pe-1 fs-14 "></span><span class="h4">2,000</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 px-0">
                        <div class="row bg-light m-0">
                            <div class="col-12 px-4 my-4">
                                <p class="fw-bold">Detalle del alquiler</p>
                            </div>
                            <div class="col-12 px-4">
                                <div class="d-flex  mb-4">
                                    <span class="">
                                        <p class="text-muted">Seleccione la nueva hora de finalizacion del alquiler: </p>
                                        <div class="form-group">
                                        <%= form.time_field :tiempo %>
                                      </div> 
                                    </span>
                                </div>
                                <div class="d-flex mb-5">
                                    <span class="me-5">
                                        <p class="text-muted">Nombre y apellido del inquilino</p>
                                        <%= current_user.name %>
                                    </span>
                                </div>
                            </div>
                        </div>
						<div class="form-check">
  							<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  							<label class="form-check-label" for="flexCheckDefault">
    							Acepto los términos y condiciones de usuario
  							</label>
                        <div class="row m-0">
                            <div class="col-12  mb-4 p-0">
                            <%= form.submit "Extender alquiler", class: 'btn btn-primary' %>
                                </div>
                            </div>
                            <% end %>

                        </div>
						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/rents/finish.html.erb
<head>
<%= stylesheet_link_tag 'bootstrap', 'wallet-styles' %>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>


<% if (Car.all.empty?) %>
 <% ensure_not_empty%>
<% end %>




<div class="container">
                <div class="row m-0 px-4">
                    <div class="col-12 px-4">
                        <div class="d-flex align-items-end mt-4 mb-2">
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="textmuted">Precio por hora</p>
                            <p class="fs-14 fw-bold"><span class="fas fa-dollar-sign pe-1"></span>1,000</p>		
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="textmuted">Precio del combustible gastado</p>
                            <p class="fs-14 fw-bold"><span class="fas fa-dollar-sign pe-1"></span>1,000</p>		
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <p class="textmuted fw-bold">Total</p>
                            <div class="d-flex align-text-top ">
                                <span class="fas fa-dollar-sign mt-1 pe-1 fs-14 "></span><span class="h4">1,000</span>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                        <p class="textmuted fw-bold">Saldo restante</p>
                        <div class="d-flex align-text-top ">
                            <span class="fas fa-dollar-sign mt-1 pe-1 fs-14 "></span><span class="h4">1,000</span>
                        </div>
                    </div>
                    </div>
                    <div class="col-12 px-0">
                        <div class="row bg-light m-0">
                            <div class="col-12 px-4 my-4">
                                <p class="fw-bold">Detalle del alquiler</p>
                            </div>
                            <div class="col-12 px-4">
                                <div class="d-flex  mb-4">
                                    <span class="">
                                        <p class="text-muted">Seleccione la hora de finalizacion del alquiler: </p>
                                        <div class="form-group">
                                      </div> 
                                    </span>
                                </div>
                                <div class="d-flex mb-5">
                                    <span class="me-5">
                                        <p class="text-muted">Nombre y apellido del inquilino</p>
                                        <%= current_user.name %>
                                    </span>
                                </div>
                            </div>
                        </div>
						<div class="form-check">
  							<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  							<label class="form-check-label" for="flexCheckDefault">
    							Acepto los términos y condiciones de usuario
  							</label>
                        <div class="row m-0">
                            <div class="col-12  mb-4 p-0">
                            <%= button_to 'Terminar Alquiler', terminar_alquiler_rent_path(@rent), method: :patch, class: "btn btn-danger" %>
                                </div>
                            </div>
                        </div>

						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/rents/index.html.erb
<head>
<%= stylesheet_link_tag 'bootstrap', 'rent-index-style' %>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
</head>
<%= ensure_log %>

<div class="container">
    <h1 class='my-3 py-3'>Mis alquileres</h1>
    <p style="color: green"><%= notice %></p>
    <div class="row">
    <% if !(@rents.empty?) then %>
    <% @rents.each do |rent| %>        
        <div class="col-lg-4">
        <div class="card card-margin">
            <div class="card-header no-border">
                <h5 class="card-title"><%= Car.find(rent.car_id).patente %> - <%= Car.find(rent.car_id).modelo %></h5>
            </div>
              <div class="card-body pt-0">
                  <div class="widget-49">
                      <div class="widget-49-title-wrapper">
                          <div class="widget-49-date-primary">
                              <span class="widget-49-date-day"><%= rent.created_at.day %>/<%= rent.created_at.month %></span>
                          </div>
                          <div class="widget-49-meeting-info">
                                <span class="widget-49-pro-title">Precio del alquiler: <b>$<%= number_with_precision rent.precio, :precision => 2 %></span></b>
                                <span class="widget-49-meeting-time">Hora de comienzo del alquiler: <%= rent.created_at.hour %>:<%= rent.created_at.min %> hs </span>
                          </div>
                      </div>
                      <ol class="widget-49-meeting-info">
                          <li class="widget-49-meeting-item"><span>Combustible gastado: <%= rent.combustible_gastado %></span></li>
                          <li class="widget-49-meeting-item"><span>Hora de finalizacion de alquiler: <%= Time.new.change(hour: rent.tiempo.hour, min: rent.tiempo.min).strftime("%H:%M")%> hs</span></li> </ol>
                      <div class="widget-49-meeting-action">
                           <%if rent.activo? %>
                                <span class="widget-49-pro-title" style="font-weight: bold; color: green" >Tiempo restante: <%=time_diff(rent.tiempo, Time.now)  %>
                            <%elsif%>
                                <span class="widget-49-pro-title" style="color:red">Alquiler finalizado</span>
                            <% end %>
                          <%= link_to "Detalles", rent, :class => "btn btn-sm btn-flash-border-primary" %>
                      </div>
                  </div>
            </div>
        </div>
</div>
<% end %>
<%else %>
    <div class='container py-4' align='center'>
	    <span class="display-1 d-block">:(</span>
        <div class="mb-4 lead">Lo sentimos, no se han encontrado alquileres.</div>
        <a href="/cars" class="btn btn-link">Realizar un alquiler...</a>
    </div>
<%end%>
</div>
</div>

app/views/rents/new.html.erb
<head>
<%= stylesheet_link_tag 'bootstrap', 'wallet-styles' %>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>

<% if (Car.all.empty?) %>
 <% ensure_not_empty%>
<% end %>

<div class="container">
                <div class="row m-0 px-4 mt-5">
                    <div class="col-12 px-4">
                        <div class="d-flex align-items-end mt-4 mb-2">
                         <%= form_with(model: @rent) do |form| %>
                      <% if @rent.errors.any? %>
                        <div style="color: red">
                          <h4><%= pluralize(@rent.errors.count, "errores") %> detectados:</h4>
                          <ul>
                            <% @rent.errors.each do |error| %>
                              <li><%= error.full_message %></li>
                            <% end %>
                          </ul>
                        </div>
                      <% end %>
                    	<%= form.hidden_field :car_id, value: params[:autito] %>
                    <br>
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="textmuted">Precio por hora</p>
                            <p class="fs-14 fw-bold"><span class="fas fa-dollar-sign pe-1"></span>1,000</p>		
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <p class="textmuted fw-bold">Total</p>
                            <div class="d-flex align-text-top ">
                                <span class="fas fa-dollar-sign mt-1 pe-1 fs-14 "></span><span class="h4">1,000</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 px-0">
                        <div class="row bg-light m-0">
                            <div class="col-12 px-4 my-4">
                                <p class="fw-bold">Detalle del alquiler</p>
                            </div>
                            <div class="col-12 px-4">
                                <div class="d-flex  mb-4">
                                    <span class="">
                                        <p class="text-muted">Seleccione la hora de finalizacion del alquiler: </p>
                                        <div class="form-group">
                                            <%= form.time_field :tiempo %>
                                      </div> 
                                    </span>
                                </div>
                                <div class="d-flex mb-5">
                                    <span class="me-5">
                                        <p class="text-muted">Nombre y apellido del inquilino</p>
                                        <%= current_user.name %>
                                    </span>
                                </div>
                            </div>
                        </div>
						<div class="form-check py-3">
  							<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  							<label class="form-check-label pb-3" for="flexCheckDefault">
    							Acepto los términos y condiciones de usuario
  							</label>
                        <div class="row m-0">
                            <div class="col-12  mb-4 p-0">
                            <%= form.submit "Alquilar", class: 'btn btn-primary' %>
                                <% end %>
                                </div>
                            </div>
                        </div>

						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/rents/show.html.erb
<style>
.hidden {
  display: none
}
</style>
<head>
    <%= stylesheet_link_tag 'bootstrap', "wallet-styles" %>    
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>
<body>
<%= javascript_include_tag "application" %>

<%= ensure_log %>

<div class="container">
        <div class="row m-0">
            <div class="col-lg-7 pb-5 pe-lg-5">
                <p style="color: green"><%= notice %></p>
                <p style="color: red"><%= alert %></p>

                <div class="row">
                    <% if Car.find(@rent.car_id).photo.attached? %>
                        <div class="col-12 p-5">
                            <%= image_tag(Car.find(@rent.car_id).photo, style:'width:100%') %>
                        </div>
                    <%elsif%>
                        <div class="col-12 p-5">
                            <img src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
                        </div>
                    <% end %>
                    <div class="row m-0 bg-light">
                        <div class="col-md-4 col-6 ps-30 pe-0 my-4">
                            <p class="text-muted">Kilometros</p>
                            <p class="h5"><%= @rent.car.kilometraje %><span class="ps-1">Km</span></p>
                        </div>
                        <div class="col-md-4 col-6  ps-30 my-4">
                            <p class="text-muted">Modelo</p>
                            <p class="h5 m-0"><%= @rent.car.modelo %></p>
                        </div>
                        <div class="col-md-4 col-6 ps-30 my-4">
                            <p class="text-muted">Patente</p>
                            <p class="h5 m-0"><%= Car.find(@rent.car_id).patente %></p>
                        </div>
                        <div class="col-md-4 col-6 ps-30 my-4">
                            <p class="text-muted">ID</p>
                            <p class="h5 m-0">#<%= @rent.car_id %></p>
                        </div>
                        <div class="col-md-4 col-6 ps-30 my-4">
                            <a href="/tickets/new" type="button" class="btn btn-primary bg-danger">Reportar un problema</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-lg-5 p-0 ps-lg-4">
                <div class="row m-0">
                    <div class="col-12 px-4">
                        <div class="d-flex align-items-end mt-4 mb-2">
                            <p class="h4 m-0"><span class="pe-1"></span></p>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <p class="textmuted fw-bold">Total</p>
                            <div class="d-flex align-text-top ">
                                <span class="fas fa-dollar-sign mt-1 pe-1 fs-14 "></span><span class="h4">$<%= number_with_precision @rent.precio, :precision => 2 %></span>
                            </div>
							<% if (user_signed_in? && @rent.activo?) %>      
							<p class="textmuted fw-bold">Tiempo restante</p>
                            <div class="d-flex align-text-top ">
                                <span class="fas fa-dollar-sign mt-1 pe-1 fs-14 "></span><span class="h4"><%=time_diff(@rent.tiempo, Time.now)  %></span>
                            </div>
							 <% end %>
                        </div>
                    </div>
                    <div class="col-12 px-0">
                        <div class="row bg-light m-0">
                            <div class="col-12 px-4 my-4">
                                <p class="fw-bold">Detalle del alquiler</p>
                            </div>
                            <div class="col-12 px-4">
                                <div class="d-flex  mb-4">
                                    <span class="">
                                        <p class="text-muted">Hora y fecha de comienzo: </p>
                                        <%= Time.new.change(year: @rent.created_at.year, month: @rent.created_at.month, day: @rent.created_at.day, hour: @rent.created_at.hour, min: @rent.created_at.min).strftime("%d/%m/%Y %H:%Mhs")%>                                          
                                    </span>
                                </div>
                                <div class="d-flex  mb-4">
                                    <span class="">
                                        <p class="text-muted">Combustible gastado: </p>
                                        <%= @rent.combustible_gastado %>
                                           
                                    </span>
                                </div>
                                <div class="d-flex mb-5">
                                    <span class="me-5">
                                        <p class="text-muted">Nombre - DNI/N° de documento del inquilino</p>
                                            <%= User.find(@rent.user_id).name %> - <%= User.find(@rent.user_id).dni %>
                                    </span>
                                </div>
                                <div class="d-flex">
                                  <span class="py-2">
                                  <% if (@rent.user_id == current_user.id) %>
                                    <%= link_to "Volver a Mis Alquileres", rents_path, :class => 'btn btn-primary my-2' %>
                                      <% if (user_signed_in? && @rent.activo? && @rent.car.estacionado?) %>   
                                    <%= link_to "Extender alquiler", edit_rent_path(@rent), :class => 'btn btn-primary my-4' %> 
                                      <% end %>
                                  <% end %>
                                  </span>
                                </div>
                                    <% if (user_signed_in? && @rent.activo? && @rent.car.estacionado? && (@rent.user_id == current_user.id)) %>              
                                        <% if !esta_en_LP then %>
                                        <div class='row px-1' style='width:100%'>
                                            <div class='col lg-6'>     
                                                <a class= 'btn btn-primary' href='#' onClick='reveal()'>Terminar alquiler</a>     
                                            </div>
                                        </div>
                                        <div class='row py-2 px-1' style='width:100%'>
                                            <div class='col lg-6'>  
                                                <div id='hidden-div' class='hidden'>
                                                    <span class="row d-flex justify-content-center align-items-center h-100 p-3" >El auto no se encuentra dentro del Casco Urbano de La Plata, se le cobrara una multa por dejarlo estacionado ahi. Esta seguro que desea terminar al alquiler?</span>
                                                    <%= button_to 'Si, terminar', terminar_alquiler_rent_path(@rent), method: :patch, class: "btn btn-danger" %>
                                                    <a class= 'btn btn-primary my-1' href='' onClick='reveal()'>No</a>       
                                                </div>
                                            </div>
                                        </div>
                                        <%else %>
                                        <div class='row px-1 py-0 mt-0' style='width:100%'>
                                            <div class='col lg-6'>     
                                                <a class= 'btn btn-primary' href='#' onClick='reveal()'>Terminar alquiler</a>     
                                            </div>
                                        </div>
                                        <div class='row py-3 my-4 px-1' style='width:100%'>
                                            <div class='col lg-6'>  
                                                <div id='hidden-div' class='hidden'>
                                                    <span class="row d-flex justify-content-center align-items-center h-100 p-3" >Esta seguro que desea terminar al alquiler?</span>
                                                    <%= button_to 'Si, terminar', terminar_alquiler_rent_path(@rent), method: :patch, class: "btn btn-danger" %>
                                                    <a class= 'btn btn-primary my-1' href='' onClick='reveal()'>No</a>       
                                                </div>
                                            </div>
                                        </div>
                                        <% end %>
                                    <%end%>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div>

<script>
  function reveal() {
    var element = document.getElementById("hidden-div");
    element.classList.remove("hidden");
  }
</script>
    