config/routes.rb
Rails.application.routes.draw do
  resources :payments
  get 'static_pages/home_logged_user'
  get '/tickets', to: 'tickets#index'

  post '/paymentNotification', to: 'payments#receive_and_update'
  post '/tickets/new', to: 'tickets#create'

  post '/password/reset', to: 'users#enviar_mail_recuperar_contrasenia'

  resources :cars
  resources :rents
  resources :payments
  resources :tickets
  devise_for :users, components: {registrations: 'registrations', sessions: 'sessions'} #Las de devise siempre tienen que estar encima de las de USER

  resources :users, only: [:show]

  resources :users do
	  member do
	  	patch :update_rango
		patch :baja_y_alta_supervisores
		patch :bloquear_usuario
	  end
  end

  resources :rents do
	member do
		patch :terminar_alquiler
	end
  end

  resources :cars do
	member do
		patch :dar_de_baja
    patch :dar_de_alta
	end
  end

  root to: "static_pages#home"
end

app/models/car.rb
class Car < ApplicationRecord

	has_many :rents, :dependent => :destroy
	has_one_attached :photo
	has_one_attached :file
	acts_as_mappable
	

	validates :patente, presence: true, uniqueness: true
	validates :modelo, presence: true
	validates_format_of :patente,:with => /\A([a-zA-Z]{2,3}[0-9]{3}[a-zA-Z]{0,2})?\z/
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    if (current_user.Admin? || current_user.Supervisor?)
      @cars = Car.all
    else
	    @cars = Car.where(alquilado: false, de_baja: false)
    end
    if params[:search_modelo] && params[:search_modelo] != ""
			@cars = @cars.where("modelo like ?", "#{params[:search_modelo]}%")
     # @cars_not_rented = @cars_not_rented.where("modelo like ?", "#{params[:search_modelo]}%")
		end
    if params[:search_kilometraje] && params[:search_kilometraje] != ""
			@cars = @cars.where("kilometraje < ?", params[:search_kilometraje])
      #@cars_not_rented = @cars_not_rented.where("kilometraje < ?", params[:search_kilometraje])
		end
    if params[:search_tanque] && params[:search_tanque] != ""
			@cars = @cars.where("tanque > ?", params[:search_tanque])
      #@cars_not_rented = @cars_not_rented.where("tanque > ?", params[:search_tanque])
		end
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Auto creado de manera exitosa." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
  set_car
  if !(@car.alquilado?)
    @car.destroy
    redirect_to cars_path, notice: "Auto eliminado de manera exitosa"
  elsif
    redirect_to car_url(@car), alert: "El auto que esta intentando eliminar se encuentra en uso."
  end
  end


  def dar_de_baja
	set_car
	if !(@car.alquilado?)
		#notice: "Auto dado de baja de manera exitosa"
		if (@car.update(de_baja: true))
			redirect_to car_url(@car), notice: "Auto dado de baja de manera exitosa"
		end
	elsif
		redirect_to car_url(@car), alert: "El auto que esta intentando dar de baja se encuentra en uso."
	end
  end

  def dar_de_alta
	  set_car
	  if (@car.de_baja?)
	  	if (@car.update(de_baja: false))
	  		redirect_to car_url(@car), notice: "Auto dado de alta de manera exitosa"
	  	end
	  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:patente, :modelo, :photo, :tanque, :kilometraje, :lat, :lng, :file)
    end  
    
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Patente:</strong>
    <%= car.patente %>
  </p>

  <p>
    <strong>Modelo:</strong>
    <%= car.modelo %>
  </p>

</div>

app/views/cars/_form.html.erb
<div class='container justify-content-center align-items-center py-5'>
  <h1>Cargar auto</h1>

    <%= form_with(model: car) do |form| %>
      <% if car.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

          <ul>
            <% car.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :patente, style: "display: block" %>
        <%= form.text_field :patente %>
      </div>

      <div>
        <%= form.label :modelo, style: "display: block" %>
        <%= form.text_field :modelo %>
      </div>

      <div>
    	<%= form.label :tanque, "Capacidad de tanque de combustible"%>
    	<%= form.number_field :tanque %>
      </div>

      <div>
    	<%= form.label :kilometraje, "Kilometraje"%>
    	<%= form.number_field :kilometraje %>
      </div>

      <div>
    	<%= form.label :photo, "Foto del auto"%>
    	<%= form.file_field :photo %>
      </div>

      <div>
      <%= form.label :file, "Reporte de incidencias"%>
      <%= form.file_field :file %>
      </div>

      <div>
    	<%= form.hidden_field :lat, value: rand(-34.943789..-34.897041) %>
      </div>

      <div>
    	<%= form.hidden_field :lng, value: rand(-57.973537..-57.933111) %>
      </div>

      <div>
        <%= form.submit "Cargar auto", :class => "btn btn-primary" %>
      </div>
    <% end %>
</div>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html_BACKUP_17160.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
<<<<<<< HEAD
  <div class="row">
    <% @cars_not_rented.each do |car| %>
      <div class="col-md-3">
          <div class="card-sl">
			<% if car.photo.attached? %>
             <div class="card-image">
                  <%= image_tag(car.photo, style:'width:100%') %>
              </div>
			<% elsif %>
				             <div class="card-image">
                  <img
                      src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
              </div>
			<% end %>

              <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
              <div class="card-heading">
                  <%= car.modelo %>
              </div>
              <div class="card-text">
                  <%= car.patente %>
              </div>
              <div class="card-text">
                  Alquiler por hora: $1000
              </div>
              <%= link_to "Alquilar", car, :class => "card-button" %>
          </div>
      </div>
      <% end %>
  </div>  
=======
        <div class="row">
        <% @cars_not_rented.each do |car| %>
            <div class="col-md-3">
                <div class="card-sl">
                    <div class="card-image">
                        <img <%= image_tag(car.photo, style:'width:100%') %>
                    </div>
                    <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                    <div class="card-heading">
                        <%= car.modelo %>
                    </div>
                    <div class="card-text">
                         
                    </div>
                    <div class="card-text">
                        $67,400
                    </div>
                    <%= link_to "Alquilar", car, :class => "card-button" %>
                </div>
            </div>
          <% end %>
        </div>  
>>>>>>> d29d3dcee1456c198a23b0f8cec851c9d3697e0f

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_BACKUP_17246.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
<<<<<<< HEAD
  <div class="row">
    <% @cars_not_rented.each do |car| %>
      <div class="col-md-3">
          <div class="card-sl">
			<% if car.photo.attached? %>
             <div class="card-image">
                  <%= image_tag(car.photo, style:'width:100%') %>
              </div>
			<% elsif %>
				             <div class="card-image">
                  <img
                      src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
              </div>
			<% end %>

              <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
              <div class="card-heading">
                  <%= car.modelo %>
              </div>
              <div class="card-text">
                  <%= car.patente %>
              </div>
              <div class="card-text">
                  Alquiler por hora: $1000
              </div>
              <%= link_to "Alquilar", car, :class => "card-button" %>
          </div>
      </div>
      <% end %>
  </div>  
=======
        <div class="row">
        <% @cars_not_rented.each do |car| %>
            <div class="col-md-3">
                <div class="card-sl">
                    <div class="card-image">
                        <img <%= image_tag(car.photo, style:'width:100%') %>
                    </div>
                    <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                    <div class="card-heading">
                        <%= car.modelo %>
                    </div>
                    <div class="card-text">
                         
                    </div>
                    <div class="card-text">
                        $67,400
                    </div>
                    <%= link_to "Alquilar", car, :class => "card-button" %>
                </div>
            </div>
          <% end %>
        </div>  
>>>>>>> d29d3dcee1456c198a23b0f8cec851c9d3697e0f

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_BASE_17160.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
        <div class="row">
        <% @cars_not_rented.each do |car| %>
            <div class="col-md-3">
                <div class="card-sl">
                    <div class="card-image">
                        <img <%= image_tag(car.photo, style:'width:100%') %>
                    </div>
                    <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                    <div class="card-heading">
                        Audi Q8
                    </div>
                    <div class="card-text">
                        Audi Q8 is a full-size luxury crossover SUV coupé made by Audi that was launched in 2018.
                    </div>
                    <div class="card-text">
                        $67,400
                    </div>
                    <%= link_to "Alquilar", car, :class => "card-button" %>
                </div>
            </div>
          <% end %>
        </div>  

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_BASE_17246.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
        <div class="row">
        <% @cars_not_rented.each do |car| %>
            <div class="col-md-3">
                <div class="card-sl">
                    <div class="card-image">
                        <img <%= image_tag(car.photo, style:'width:100%') %>
                    </div>
                    <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                    <div class="card-heading">
                        Audi Q8
                    </div>
                    <div class="card-text">
                        Audi Q8 is a full-size luxury crossover SUV coupé made by Audi that was launched in 2018.
                    </div>
                    <div class="card-text">
                        $67,400
                    </div>
                    <%= link_to "Alquilar", car, :class => "card-button" %>
                </div>
            </div>
          <% end %>
        </div>  

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_LOCAL_17160.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
  <div class="row">
    <% @cars_not_rented.each do |car| %>
      <div class="col-md-3">
          <div class="card-sl">
			<% if car.photo.attached? %>
             <div class="card-image">
                  <%= image_tag(car.photo, style:'width:100%') %>
              </div>
			<% elsif %>
				             <div class="card-image">
                  <img
                      src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
              </div>
			<% end %>

              <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
              <div class="card-heading">
                  <%= car.modelo %>
              </div>
              <div class="card-text">
                  <%= car.patente %>
              </div>
              <div class="card-text">
                  Alquiler por hora: $1000
              </div>
              <%= link_to "Alquilar", car, :class => "card-button" %>
          </div>
      </div>
      <% end %>
  </div>  

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_LOCAL_17246.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
  <div class="row">
    <% @cars_not_rented.each do |car| %>
      <div class="col-md-3">
          <div class="card-sl">
			<% if car.photo.attached? %>
             <div class="card-image">
                  <%= image_tag(car.photo, style:'width:100%') %>
              </div>
			<% elsif %>
				             <div class="card-image">
                  <img
                      src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
              </div>
			<% end %>

              <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
              <div class="card-heading">
                  <%= car.modelo %>
              </div>
              <div class="card-text">
                  <%= car.patente %>
              </div>
              <div class="card-text">
                  Alquiler por hora: $1000
              </div>
              <%= link_to "Alquilar", car, :class => "card-button" %>
          </div>
      </div>
      <% end %>
  </div>  

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_REMOTE_17160.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
        <div class="row">
        <% @cars_not_rented.each do |car| %>
            <div class="col-md-3">
                <div class="card-sl">
                    <div class="card-image">
                        <img <%= image_tag(car.photo, style:'width:100%') %>
                    </div>
                    <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                    <div class="card-heading">
                        <%= car.modelo %>
                    </div>
                    <div class="card-text">
                         
                    </div>
                    <div class="card-text">
                        $67,400
                    </div>
                    <%= link_to "Alquilar", car, :class => "card-button" %>
                </div>
            </div>
          <% end %>
        </div>  

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/index.html_REMOTE_17246.erb
<head>
<%= stylesheet_link_tag 'bootstrap' %>
<%= stylesheet_link_tag 'cars-index-styles'%>
</head>
<%= render 'shared/nav' if user_signed_in? %>


<p style="color: green"><%= notice %></p>


<h1>Vehiculos disponibles</h1>



<% if !Car.where(alquilado: false).empty? %>

<div class="container" style="margin-top:50px;">
        <div class="row">
        <% @cars_not_rented.each do |car| %>
            <div class="col-md-3">
                <div class="card-sl">
                    <div class="card-image">
                        <img <%= image_tag(car.photo, style:'width:100%') %>
                    </div>
                    <a class="card-action" href="#"><i class="fa fa-heart"></i></a>
                    <div class="card-heading">
                        <%= car.modelo %>
                    </div>
                    <div class="card-text">
                         
                    </div>
                    <div class="card-text">
                        $67,400
                    </div>
                    <%= link_to "Alquilar", car, :class => "card-button" %>
                </div>
            </div>
          <% end %>
        </div>  

<% elsif %>
         <img
                      src="https://cdn.motor1.com/images/mgl/QRK8Z/s3/10-cars-that-could-disappear-soon.webp" />
         </div>
<% end %>


  <%= turbo_frame_tag "modal" %>

<% if (user_signed_in? && !!current_user.Admin?) %>
	<%= link_to "Nuevo auto", new_car_path %>
<% end %>



  

app/views/cars/new.html.erb
<head>
	<%= stylesheet_link_tag 'bootstrap'%>
	<%= stylesheet_link_tag 'login-styles'%>
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

</head>
<%= ensure_adm %>
<%= render "form", car: @car %>

<br>

app/views/cars/show.html.erb
<style>
.hidden {
  display: none
}
</style>
<head>
    <%= ensure_log %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'bootstrap', "wallet-styles" %>    
</head>
<body>
<div class="container">
    
        <div class="row m-0 h-100">
            <div class="col-lg-7 pe-lg-5 pt-4">    
            <p class='px-5' style="color: green"><%= notice %></p>
            <p class='px-5' style="color: red"><%= alert %></p>
                <div class="row">
                    <% if @car.photo.attached? %>
                        <div class="col-12 p-5">
                            <%= image_tag(@car.photo, style:'width:100%') %>
                        </div>
                    <%elsif%>
                        <div class="col-12 p-5">
                            <img src="https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
                        </div>
                    <% end %>
                    <div class="row mb-3 ml-3 bg-light">
                        <div class="col-md-4 col-6 ps-30 pe-0 my-4">
                            <p class="text-muted">Kilometros</p>
                            <p class="h5"><%= @car.kilometraje %><span class="ps-1">Km</span></p>
                        </div>
                        <div class="col-md-4 col-6  ps-30 my-4">
                            <p class="text-muted">Modelo</p>
                            <p class="h5 m-0"><%= @car.modelo %></p>
                        </div>
                        <div class="col-md-4 col-6 ps-30 my-4">
                            <p class="text-muted">Patente</p>
                            <p class="h5 m-0"><%= @car.patente %></p>
                        </div>
                        <div class="col-md-4 col-6 ps-30 my-4">
                            <p class="text-muted">ID</p>
                            <p class="h5 m-0">#<%= @car.id %></p>
                        </div>
                        <div class="col-md-4 col-6 ps-30 my-4">
                            <p class="text-muted">Estado</p>
                            <% if !(@car.de_baja) then %>
                                <p class="h5 m-0">Disponible</p>
                            <% else %>
                                <p class="h5 m-0">Dado de baja</p>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 p-0 ps-lg-4 mt-3 pb-5 mb-5">
                <div class="row m-0">
                    <div class="col-12 px-4">
                        <div class="d-flex align-items-end mt-4 mb-2">
                            <p class="h4 m-0"><span class="pe-1"><%= @car.modelo %></span></p>
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="textmuted">Precio por hora</p>
                            <p class="fs-14 fw-bold"><span class="fas fa-dollar-sign pe-1" style='height:10px'></span>1,000</p>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <p class="textmuted fw-bold">Total</p>
                            <div class="d-flex align-text-top ">
                                <span class="fas fa-dollar-sign mt-1 pe-1 fs-14"></span><span class="h4">1,000</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 px-0">
                    <% if current_user.rango == "Usuario" %>
                        <div class="row bg-light m-0">
                            <div class="col-12 px-4 my-4">
                                <p class="fw-bold">Detalle de pago</p>
                            </div>
                            <div class="col-12 px-4">
                                <div class="d-flex  mb-4">
                                    <span class="">
                                        <p class="text-muted">Saldo actual: </p><%= number_with_precision current_user.saldo, :precision => 2 %>
                                    </span>
                                </div>
                                <div class="d-flex mb-5">
                                    <span class="me-5">
                                        <p class="text-muted">Nombre y apellido del inquilino</p>
                                            <%= current_user.name %>
                                    </span>
                                </div>
                            </div>
                    <% end %>
                        </div>
                        <% if (user_signed_in? && current_user.Usuario?)%>
                        <div class="row m-0">
                            <div class="col-12  mb-4 py-4">
                                <div class="row ml-4">
                                <%= link_to "Siguiente", new_rent_path(autito: @car), :class => "btn btn-primary" %>
                                </div>
                                </div>
                            </div>
                        </div>
                        <div class="row m-0">
                        <div class="col-12  mb-4 py-4">
                            <div class="row ml-4">
                            <%= link_to "Descargar informe de incidencias", @car.file, download: '', :class => "btn btn-primary" %>
                            </div>
                            </div>
                        </div>
                    </div>
                        <% elsif (user_signed_in? && !!current_user.Admin?) %>
                                <div class='row py-4 px-4' style='width:50%'>
                                    <div class='col lg-6'> 
                                        <!-- % = button_to "Editar Auto",@car, :class => "btn btn-primary"% -->
                                        <button class='btn btn-primary' onclick="alert('Disculpe, estamos trabajando en esa funcionalidad!')"> Editar auto</button>
                                    </div>
                                </div>
								<% if (!@car.de_baja?) %>
                                <div class='row py-4 px-4' style='width:50%'>
									<div class='col mt-6'> 
                                        <%= button_to "Dar de baja", dar_de_baja_car_path(@car), method: :patch, :class => "btn btn-primary bg-danger"%>
                                    </div>
                                </div>
								<% else %>
                                <div class='row py-4 px-4' style='width:50%'>
									<div class='col mt-6'> 
                                        <%= button_to "Dar de alta", dar_de_alta_car_path(@car), method: :patch, :class => "btn btn-primary bg-success"%>
                                    </div>
								</div>
                                <% end %>
                                <div class='row py-4 px-4' style='width:100%'>
                                    <div class='col-lg-6'>
                                    <a class= 'btn btn-primary' href='#' onClick='reveal()'>Borrar auto</a> 
                                    <div id='hidden-div' class='hidden'>
                                        <span class="row d-flex justify-content-center align-items-center h-100 p-3 " >¿Esta seguro de que desea borrar el auto?</span>
                                        <%= button_to "Si, borrar", @car, method: :delete, :class => "btn btn-danger my-1" %>
                                        <a class= 'btn btn-primary my-1' href='' onClick='reveal()'>No</a> 
                                        </div>
                                    </div>
                                </div>
						<% elsif (user_signed_in? && !!current_user.Supervisor?) %>
								<% if (!@car.de_baja?) %>
									<div class='col-lg-6'> 
                                        <%= button_to "Dar de baja", dar_de_baja_car_path(@car), method: :patch, :class => "btn btn-primary"%>
                                    </div>
								<% else %>
									<div class='col-lg-6'> 
                                        <%= button_to "Dar de alta", dar_de_alta_car_path(@car), method: :patch, :class => "btn btn-primary"%>
                                    </div>
								<% end %>								   
						<% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
  function reveal() {
    var element = document.getElementById("hidden-div");
    element.classList.remove("hidden");
  }
</script>