config/routes.rb
Rails.application.routes.draw do
  resources :payments
  get 'static_pages/home_logged_user'
  get '/tickets', to: 'tickets#index'

  post '/paymentNotification', to: 'payments#receive_and_update'
  post '/tickets/new', to: 'tickets#create'

  post '/password/reset', to: 'users#enviar_mail_recuperar_contrasenia'

  resources :cars
  resources :rents
  resources :payments
  resources :tickets
  devise_for :users, components: {registrations: 'registrations', sessions: 'sessions'} #Las de devise siempre tienen que estar encima de las de USER

  resources :users, only: [:show]

  resources :users do
	  member do
	  	patch :update_rango
		patch :baja_y_alta_supervisores
		patch :bloquear_usuario
	  end
  end

  resources :rents do
	member do
		patch :terminar_alquiler
	end
  end

  resources :cars do
	member do
		patch :dar_de_baja
    patch :dar_de_alta
	end
  end

  root to: "static_pages#home"
end

app/views/layouts/_header.html.erb
<% if !user_signed_in? %> 
	<%= link_to 'Registrar', new_user_registration_path%>
	<%= link_to 'Iniciar Sesion', new_user_session_path%>
<% else %>
	<%= button_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
	<%= link_to 'Mi perfil', user_path(current_user)%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'Logo_3-removebg-preview.png'%>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
   </head>

  <% if user_signed_in? %>
      <head>
        <title>Alquilapp - Home</title>
        <%= stylesheet_link_tag 'bootstrap','user-home-styles', 'billetera-styles' %>
      </head>
    <body>
    <div class="d-flex" id="wrapper">
      <div class="border-end bg-white" id="sidebar-wrapper">
        <div class="sidebar-heading border-bottom bg-light pb-3 text-muted">BetaSoftware™ </div>
        <div class="list-group list-group-flush">
          <% if !(current_user.A_Verificar? || current_user.Baneado? || current_user.No_Aceptado?) %>
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/">Home</a>
			      <% if !(current_user.alquilando?) %>
              <% if (user_signed_in? && !!current_user.Usuario?) %>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/cars">Alquilar</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/rents">Mis alquileres</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/tickets">Reportar un problema</a>

              <% elsif %>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/cars">Gestion de autos</a>
              <% end %>  
            <% elsif %>
              <a class="list-group-item list-group-item-action list-group-item-light p-3" <%= link_to "Estado del alquiler", current_user.rents.last %>
			      <% end %>
              <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/payments">Billetera</a>
              <a class="list-group-item list-group-item-action list-group-item-light p-3" <%= link_to "Perfil", current_user %> 
            <% if ((user_signed_in? && !!current_user.Admin?) || (user_signed_in? && !!current_user.Supervisor?)) %>
              <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/users">Gestión de usuarios</a>
              <% if (user_signed_in? && !!current_user.Admin?) %>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" <%= link_to "Nuevo auto", new_car_path %>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/tickets">Reportes</a> 
              <% end %>
            <% end %>
          <% elsif %>
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/">Home</a>
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/users/edit">Perfil</a>
          <% end %>
          
        </div>
      </div>
      <!-- Page content wrapper-->
      <div id="page-content-wrapper">
        <!-- Top navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom pb-1 ">
          <div class="container-fluid">
                <div class='col' align='left'>
                  <button class='btn btn-primary float-left' id='sidebarToggle'>Menu lateral</button>
                </div>
                <div class='col' align='center'>
                  <%= image_tag "Logo_3-removebg-preview.png", height: 40, :class => "btn float-center" %>
                  <a class="navbar-brand" href="/">Alquilapp</a>
                </div>
                <div class='col' align='right'>
                <button class="navbar-toggler navbar-toggler-right bg-light text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                </div>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                  <ul class="navbar-nav mx-auto ms-auto py-2">
                    <li>
                      <%= button_to "Cerrar sesion", destroy_user_session_path, method: :delete, type:"button", class:"btn btn-primary mx-3 my-1 float-right" , id:'sidebarToggle' %> 
                    </li>
                  </ul>
              </div>  
          </div>
        </nav>
        <!-- Page content-->
          <%= yield%>
      </div>
    </div>
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Alquilapp 2022</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->
    
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script>
      window.addEventListener('DOMContentLoaded', event => {
          const sidebarToggle = document.body.querySelector('#sidebarToggle');
          if (sidebarToggle) {
              sidebarToggle.addEventListener('click', event => {
                  event.preventDefault();
                  document.body.classList.toggle('sb-sidenav-toggled');
                  localStorage.setItem('sb|sidebar-toggle', document.body.classList.contains('sb-sidenav-toggled'));
              });
          }
      });
     window.addEventListener('DOMContentLoaded', event => {
            // Navbar shrink function
            var navbarShrink = function () {
                const navbarCollapsible = document.body.querySelector('#mainNav');
                if (!navbarCollapsible) {
                    return;
                }
                if (window.scrollY === 0) {
                    navbarCollapsible.classList.remove('navbar-shrink')
                } else {
                    navbarCollapsible.classList.add('navbar-shrink')
                }
        };

        // Shrink the navbar 
        navbarShrink();

        // Shrink the navbar when page is scrolled
        document.addEventListener('scroll', navbarShrink);

        // Activate Bootstrap scrollspy on the main nav element
        const mainNav = document.body.querySelector('#mainNav');
        if (mainNav) {
            new bootstrap.ScrollSpy(document.body, {
                target: '#mainNav',
                offset: 74,
            });
        };

        // Collapse responsive navbar when toggler is visible
        const navbarToggler = document.body.querySelector('.navbar-toggler');
        const responsiveNavItems = [].slice.call(
            document.querySelectorAll('#navbarResponsive .nav-link')
        );
        responsiveNavItems.map(function (responsiveNavItem) {
            responsiveNavItem.addEventListener('click', () => {
                if (window.getComputedStyle(navbarToggler).display !== 'none') {
                    navbarToggler.click();
                }
            });
        });

    });
    </script>
  </body>
  <% else %>
      <%= yield %>
  <% end %>
    

</html>